version: "3.8"

services:
  db:
    image: postgres:9
    user: postgres
    container_name: db
    hostname: db
    environment:
      POSTGRES_DB: ${DB_NAME:-limesurvey}
      POSTGRES_USER: ${DB_USER:-limesurvey}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-example}
    volumes:
      - ./db/data:/var/lib/postgresql/data:delegated   

  app:
    # image: acspri/limesurvey
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:80
    # http://localhost:8080/index.php/admin/authentication/sa/login
    environment: 
      DB_TYPE: ${DB_TYPE:-pgsql}
      POSTGRESQL_DB_HOST: ${DB_HOST:-db}
      POSTGRESQL_PORT: ${DB_PORT:-5432}
      POSTGRESQL_DB_NAME: ${DB_NAME:-limesurvey}
      POSTGRESQL_USERNAME: ${DB_USER:-limesurvey}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD:-example}
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-password}
      ADMIN_NAME: ${ADMIN_NAME:-Administrator}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-gary.t.wong@gov.bc.ca}
      # DEBUG: 2
      # SQL_DEBUG: 1
    volumes:
      - ./backend/plugins:/var/www/html/plugins:delegated
      - ./backend/upload:/var/www/html/upload:delegated
      - ./backend/config:/var/www/html/application/config:delegated
    depends_on:
      - db
