---
kind: Template
apiVersion: v1
metadata:
  name: nrmlimesurvey-app-dc
parameters:
  - description: The OpenShift Namespace where the ImageStream resides.
    displayName: Namespace
    name: IS_NAMESPACE
    value: 245e18-tools
  - description: The OpenShift ImageStream name.
    displayName: Image Stream
    name: IS_NAME
    value: limesurvey-bcgov
  - description: Version of LimeSurvey image to be used (e.g. v.3.16).
    displayName: Version of LimeSurvey
    name: IS_VERSION
    value: 5.1.4
  - description: The short-name of the Survey Service, lower-case with hyphen.
    displayName: LimeSurvey Acronym
    name: SURVEY_NAME
    required: true
    value: nrm
  - description: The disk space reserved for LimeSurvey uploads.
    displayName: Upload Folder size
    name: UPLOAD_FOLDER_CAPACITY
    value: 1Gi
  - description: The account name for the default LimeSurvey Administrator.
    displayName: Administrator Account Name
    name: ADMIN_USER
    value: admin
  - description: The descriptive name for the default LimeSurvey Administrator.
    displayName: Administrator Display Name
    name: ADMIN_NAME
    value: Administrator
  - description: Password for the default LimeSurvey Administrator.
    displayName: Administrator Password
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    name: ADMIN_PASSWORD
    required: true
  - description: The email address for the default LimeSurvey Administrator.
    displayName: Administrator Email Address
    name: ADMIN_EMAIL
    required: true
  - description: The type of relational database (pgsql / mysql ); currently only pgsql is supported
    displayName: Database Type
    name: DB_TYPE
    value: pgsql
  - name: CPU_LIMIT
    value: 200m
  - name: MEMORY_LIMIT
    value: 512Mi
  - name: CPU_REQUEST
    value: 50m
  - name: MEMORY_REQUEST
    value: 200Mi
  - name: REPLICA_MIN
    value: "2"
  - name: REPLICA_MAX
    value: "3"
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-app"
      labels:
        app: "${SURVEY_NAME}limesurvey"
      annotations:
        description: Application Administrator credentials and name.
        template.openshift.io/expose-admin_username: "{.data['admin-user']}"
        template.openshift.io/expose-admin_name: "{.data['admin-name']}"
        template.openshift.io/expose-admin_password: "{.data['admin-password']}"
        template.openshift.io/expose-admin_email: "{.data['admin-email']}"
    stringData:
      admin-user: "${ADMIN_USER}"
      admin-name: "${ADMIN_NAME}"
      admin-password: "${ADMIN_PASSWORD}"
      admin-email: "${ADMIN_EMAIL}"
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-app-upload"
      labels:
        app: "${SURVEY_NAME}limesurvey"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: "${UPLOAD_FOLDER_CAPACITY}"
      storageClassName: netapp-file-standard
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-app-config"
      labels:
        app: "${SURVEY_NAME}limesurvey"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 128Mi
      storageClassName: netapp-file-standard
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-app-plugins"
      labels:
        app: "${SURVEY_NAME}limesurvey"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 128Mi
      storageClassName: netapp-file-standard
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-app"
      generation: 1
      labels:
        app: "${SURVEY_NAME}limesurvey"
      annotations: {}
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${SURVEY_NAME}limesurvey-app"
            from:
              kind: ImageStreamTag
              namespace: "${IS_NAMESPACE}"
              name: "${IS_NAME}:${IS_VERSION}"
      replicas: "${{REPLICA_MIN}}"
      revisionHistoryLimit: 10
      test: false
      selector:
        app: "${SURVEY_NAME}limesurvey"
        deploymentconfig: "${SURVEY_NAME}limesurvey-app"
      template:
        metadata:
          labels:
            app: "${SURVEY_NAME}limesurvey"
            deploymentconfig: "${SURVEY_NAME}limesurvey-app"
          annotations: {}
        spec:
          volumes:
            - name: "${SURVEY_NAME}limesurvey-app-upload"
              persistentVolumeClaim:
                claimName: "${SURVEY_NAME}limesurvey-app-upload"
            - name: "${SURVEY_NAME}limesurvey-app-config"
              persistentVolumeClaim:
                claimName: "${SURVEY_NAME}limesurvey-app-config"
            - name: "${SURVEY_NAME}limesurvey-app-plugins"
              persistentVolumeClaim:
                claimName: "${SURVEY_NAME}limesurvey-app-plugins"
          containers:
            - name: "${SURVEY_NAME}limesurvey-app"
              image: " "
              command: ["/bin/sh"]
              # args: ["-c", "docker-entrypoint.sh apache2-foreground"]
              args:
                [
                  "-c",
                  "dockerize -wait tcp://${POSTGRESQL_DB_HOST}:${POSTGRESQL_PORT} -timeout 30s",
                  "-- docker-entrypoint.sh apache2-foreground",
                ]
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
              env:
                - name: ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: "${SURVEY_NAME}limesurvey-app"
                      key: admin-user
                - name: ADMIN_NAME
                  valueFrom:
                    secretKeyRef:
                      name: "${SURVEY_NAME}limesurvey-app"
                      key: admin-name
                - name: ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "${SURVEY_NAME}limesurvey-app"
                      key: admin-password
                - name: ADMIN_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: "${SURVEY_NAME}limesurvey-app"
                      key: admin-email
                - name: DB_TYPE
                  value: "${DB_TYPE}"
                - name: POSTGRESQL_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: "${SURVEY_NAME}limesurvey-postgresql"
                      key: database-user
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "${SURVEY_NAME}limesurvey-postgresql"
                      key: database-password
                - name: POSTGRESQL_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: "${SURVEY_NAME}limesurvey-postgresql"
                      key: database-name
                - name: POSTGRESQL_DB_HOST
                  value: "${SURVEY_NAME}limesurvey-postgresql"
                - name: POSTGRESQL_PORT
                  value: "5432"
              resources:
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
              volumeMounts:
                - name: "${SURVEY_NAME}limesurvey-app-upload"
                  mountPath: "/var/www/html/upload"
                - name: "${SURVEY_NAME}limesurvey-app-config"
                  mountPath: "/var/www/html/config"
                - name: "${SURVEY_NAME}limesurvey-app-plugins"
                  mountPath: "/var/www/html/plugins"
              livenessProbe:
                httpGet:
                  path: "/"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 5
                periodSeconds: 30
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: "/"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 5
                periodSeconds: 30
                successThreshold: 1
                failureThreshold: 10
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  - apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    metadata:
      name: "${SURVEY_NAME}limesurvey-app"
      labels:
        app: "${SURVEY_NAME}limesurvey"
    spec:
      maxReplicas: "${{REPLICA_MAX}}"
      minReplicas: "${{REPLICA_MIN}}"
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        name: "${SURVEY_NAME}limesurvey-app"
      targetCPUUtilizationPercentage: 95
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-app"
      labels:
        app: "${SURVEY_NAME}limesurvey"
      annotations:
        description: Exposes and load balances the application pods
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: "${SURVEY_NAME}limesurvey"
        deploymentconfig: "${SURVEY_NAME}limesurvey-app"
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-app"
      creationTimestamp:
      labels:
        app: "${SURVEY_NAME}limesurvey"
    spec:
      host: "${SURVEY_NAME}limesurvey.apps.silver.devops.gov.bc.ca"
      to:
        kind: Service
        name: "${SURVEY_NAME}limesurvey-app"
        weight: 100
      port:
        targetPort: web
      tls:
        termination: edge
      wildcardPolicy: None
