---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: nrmlimesurvey-postgresql-dc
parameters:
  - description: The short-name of the Survey Service, lower-case with hyphen.
    displayName: Survey Name
    name: SURVEY_NAME
    required: true
    value: mds
  - description: Maximum amount of memory the container can use.
    displayName: Memory Limit
    name: MEMORY_LIMIT
    required: true
    value: 512Mi
  - description: Password for the PostgreSQL connection user.
    displayName: PostgreSQL Connection Password
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    name: POSTGRESQL_PASSWORD
    required: true
  - description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Database Volume Capacity
    name: DB_VOLUME_CAPACITY
    required: true
    value: 1Gi
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-postgresql"
      labels:
        app: "${SURVEY_NAME}limesurvey"
      annotations:
        description: Database credentials and name.
        template.openshift.io/expose-database_name: "{.data['database-name']}"
        template.openshift.io/expose-password: "{.data['database-password']}"
        template.openshift.io/expose-username: "{.data['database-user']}"
    stringData:
      database-name: "${SURVEY_NAME}"
      database-password: "${POSTGRESQL_PASSWORD}"
      database-user: "${SURVEY_NAME}"
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-postgresql"
      labels:
        app: "${SURVEY_NAME}limesurvey"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${DB_VOLUME_CAPACITY}"
      storageClassName: netapp-block-standard
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-postgresql"
      labels:
        app: "${SURVEY_NAME}limesurvey"
      annotations: {}
    spec:
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${SURVEY_NAME}limesurvey-postgresql"
            from:
              kind: ImageStreamTag
              namespace: openshift
              name: postgresql:12
      replicas: 1
      revisionHistoryLimit: 10
      test: false
      selector:
        app: "${SURVEY_NAME}limesurvey"
        deploymentconfig: "${SURVEY_NAME}limesurvey-postgresql"
      template:
        metadata:
          creationTimestamp:
          labels:
            app: "${SURVEY_NAME}limesurvey"
            deploymentconfig: "${SURVEY_NAME}limesurvey-postgresql"
          annotations: {}
        spec:
          volumes:
            - name: postgresql-volume
              persistentVolumeClaim:
                claimName: "${SURVEY_NAME}limesurvey-postgresql"
          containers:
            - name: "${SURVEY_NAME}limesurvey-postgresql"
              image: " "
              ports:
                - containerPort: 5432
                  protocol: TCP
              env:
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: "${SURVEY_NAME}limesurvey-postgresql"
                      key: database-name
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "${SURVEY_NAME}limesurvey-postgresql"
                      key: database-password
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: "${SURVEY_NAME}limesurvey-postgresql"
                      key: database-user
              resources:
                limits:
                  memory: "${MEMORY_LIMIT}"
              volumeMounts:
                - name: postgresql-volume
                  mountPath: "/var/lib/pgsql/data"
              livenessProbe:
                initialDelaySeconds: 30
                tcpSocket:
                  port: 5432
                timeoutSeconds: 1
              readinessProbe:
                exec:
                  command:
                    - "/bin/bash"
                    - "-c"
                    - pg_isready -h localhost -p 5432
                initialDelaySeconds: 20
                timeoutSeconds: 1
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${SURVEY_NAME}limesurvey-postgresql"
      labels:
        app: "${SURVEY_NAME}limesurvey"
      annotations: {}
    spec:
      ports:
        - name: 5432-tcp
          protocol: TCP
          port: 5432
          targetPort: 5432
      selector:
        app: "${SURVEY_NAME}limesurvey"
        deploymentconfig: "${SURVEY_NAME}limesurvey-postgresql"
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
